name = input("What is your name?")
print(f"Hello {name} I am norbert your personal chatbot")
print("I am going to ask you some questions about you.")
emotion = input("How are you feeling?")
why =  input(f"Why are you feeling {emotion} ")
print("I would feel the same if that happened to me")
clas = input("Whats your favorite class.")
print(f"cool! I also love {clas}")
sport = input("whats your favorite sport")
print("Wow!")
print(f"{sport} Is fun but gloving is better.")
print("Watch this")
print("dkfjskdfsdfsdkfjaslkdfjalkdsjfalksdjfalksdjflakjdsflkajsdflk")
print("nevermind im not doing that it dont work")
print("Goodbye i hope you enjoyed your experince")